{% set name = "dpgen" %}
{% set version = "0.13.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c0c0369a9775262f8b4f814761b56fc43d2c50cf61bc8ef5d4499ee4d5cae9db

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dpgen = dpgen.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - numpy >=1.14.3
    - dpdata >=0.2.16
    - pymatgen >=2022.11.1
    - ase
    - monty >2.0.0
    - paramiko
    - custodian
    - openbabel
    - gromacswrapper >=0.8.0
    - dpdispatcher >=0.3.11
    - netcdf4
    - dargs >=0.4.0
    - h5py
    - pymatgen-analysis-defects
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - dpgen
  commands:
    - dpgen -h

about:
  home: https://github.com/deepmodeling/dpgen
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: The deep potential generator
  doc_url: https://docs.deepmodeling.com/projects/dpgen/
  dev_url: https://github.com/deepmodeling/dpgen

extra:
  recipe-maintainers:
    - njzjz
