{% set name = "dpgen" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2421eeb8db54d542be865504d29e56afb893bff1500d5a073b415d00a35852c8
  patches:
    - add_version.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - dpgen = dpgen.main:main

requirements:
  host:
    - python >=3.5
    - pip
    - m2r
  run:
    - python >=3.5
    - numpy >=1.14.3
    - dpdata >=0.1.7
    - pymatgen >=2017.9.1
    - ase
    - monty >2.0.0
    - paramiko
    - custodian
    - openbabel

test:
  imports:
    - dpgen
  commands:
    - dpgen -h

about:
  home: https://github.com/deepmodeling/dpgen
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'The deep potential generator'
  doc_url: https://github.com/deepmodeling/dpgen
  dev_url: https://github.com/deepmodeling/dpgen

extra:
  recipe-maintainers:
    - njzjz
