{% set name = "dpgen" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5f9413bca5808b171aa4c53b833a612e4cb7f0ff2c6fb60425d3a17c779d5fa6

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dpgen = dpgen.main:main

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
    - m2r
  run:
    - python >=3.5
    - numpy >=1.14.3
    - dpdata >=0.1.10
    - pymatgen >=2017.9.1
    - ase
    - monty >2.0.0
    - paramiko
    - custodian
    - openbabel

test:
  imports:
    - dpgen
  commands:
    - dpgen -h

about:
  home: https://github.com/deepmodeling/dpgen
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: The deep potential generator
  doc_url: https://github.com/deepmodeling/dpgen
  dev_url: https://github.com/deepmodeling/dpgen

extra:
  recipe-maintainers:
    - njzjz
