travis:
  secure:
    BINSTAR_TOKEN: xpZFPN9f/RVgRj/1clRrl4Wk9hXkhgclhidXSIHDTkjpmk/qzjiGJAxg2Rmf6Vx84TyGvHWD79ukFCZPT/ucqAeUnP0vSxobHMN62d6XQ2vgOT35oJEcKXuodGnIZ06SmVemNkzUQbUHGpNKhkeycHAdqWR/GkvAVFaqfulKu7u97FOslwlb0RHVp/OFDEUeJuWQvZTO2j56AMMdB6axyzEwDW9oAn8+7gQ51xX2CfeY4Sfc/hLUQTTh6ALyFTr5vWfXA5UkfsvxrHZUisSTJSLsYfwPxnvRVgxn6A0K5OkhL2gS45RR3bBfidH7Db4Rd7kiIx+SNk4x8UDCNToa2JWXc7KSlqQVygIiJz3DgJWQPG0JJX1JA5FeI5FAo6lAb+0tzTlAsdgJt4Fb7TY7e4ZP0jZ4XvDDgGEHrN79jF+H3Tdm9TnlZpse0v5lJq99T8A7hO9wkQaJNFUxyZGb6k6rQNJB7XaDL9jGo40yleJkKlZnozChEe69SuONF8btNwCLIBFCUIwiJC/VaT6pjxehrRpsVcVqD9Arb7UTvUkt5FF42hRL2eckI+MHdDB0J/P6/Ue27cXHjRbkFFDBb64SoK8ivRP2vW4gUlJz+SQOwHSo3s6dq2sXgKiknYJK5dCGaQiK3Hb6a2QZ9soErBCeWrPmrksmznBvlIN2iyA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
